function [fitresult, gof] = createFit2(ukxmax, kymax,Smoothness)
%CREATEFIT2(UKXMAX,KYMAX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: ukxmax
%      Y Output: kymax
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Sep-2022 15:19:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( ukxmax, kymax );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = Smoothness;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'kymax vs. ukxmax', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'ukxmax', 'Interpreter', 'none' );
% ylabel( 'kymax', 'Interpreter', 'none' );
% grid on


